### PR TITLE
Use computed properties in input helpers

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by bvaughn** [comment]
Just curious...why? :)

**Comment by bvaughn** [comment]
By the way, looks like TypeScript doesn't support computed properties Microsoft/TypeScript#1811. It's not even on their roadmap yet, beyond "spec it out". So I'm going to close this.

**Comment by mohsen1** [comment]
This PR is not a big deal. So don't worry about it. Looking at the produced code I see it does support computed properties. Maybe because we are using alpha TypeScript it has edgy features

**Comment by bvaughn** [comment]
I would consider "supporting computed properties" as "recognizes and transpiles them" since at this point _no one_ supports them outside of recent Firefox. I don't think we should change 3 lines to 2 lines when those 2 lines aren't supported by anyone _unless_ we're going to transpile it

**Pull request closed without merging**
